### ISSUE TITLE
Can't seem to make typeahead to work.

### ISSUE THREAD

**Issue by Malavos** [bassjobsen/Bootstrap-3-Typeahead#158]
So, I made two trials on making Typeahead working. One with the old one (which includes Typeahead.bundle.js), and many more with this version here.

What I ended having on my last trials:

                $("#autoCompleteTypeAhead").typeahead({
                    hint: true,
                    highlight: true,
                    minLength: 1
                },
                {
                    name: "arrJson",
                    source: arrJson
                });

This was my first shot. ArrJson is like so: 

["ABINADABE MATOS ", "ADRIANO MELO", "ALBERTO ARAUJO", "VARELA"]

Couple of names. if I give console.log before that function, arrJson is filled correctly.
That function is executed accordlingly, but the autocomplete does not work with the input, and that's the result, at HTML level:

<input class="typeahead" type="text" id="autoCompleteTypeAhead" data-provide="typeahead" autocomplete="off" placeholder="Pesquise uma pessoa para iniciar o atendimento" style="width: 100% !important;">

I also tried in other way:

                $("#autoCompleteTypeAhead").typeahead({
                    hint: true,
                    highlight: true,
                    minLength: 1
                },
                {
                    name: "arrJson",
                    source: function(query, process) {
                        return process(arrJson);
                    }
                });

Neither works. What I'm doing wrong?

**Comment by patelnav** [comment]
You're passing options as a second parameter to typeahead()
Combine all your options into a single Object: 
            $("#autoCompleteTypeAhead").typeahead({
                hint: true,
                highlight: true,
                minLength: 1,
                source: arrJson
            });

**Comment by Malavos** [comment]
@patelnav  this worked nicely, but the style what a bit off.

I inserted this to fix it to my CSS, and I will share in case other folks have the same problem with CSS as well:

```CSS
.tt-query {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075) !important;
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075) !important;
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075) !important;
}

.tt-hint {
    color: #999 !important;
}

.tt-menu {    /* used to be tt-dropdown-menu in older versions */
  width: 422px !important;
  margin-top: 4px !important;
  padding: 4px 0 !important;
  background-color: #fff !important;
  border: 1px solid #ccc !important;
  border: 1px solid rgba(0, 0, 0, 0.2) !important;
  -webkit-border-radius: 4px !important;
     -moz-border-radius: 4px !important;
          border-radius: 4px !important;
  -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2) !important;
     -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2) !important;
          box-shadow: 0 5px 10px rgba(0,0,0,.2) !important;
}

.tt-suggestion {
  padding: 3px 20px !important;
  line-height: 24px !important;
}

.tt-suggestion.tt-cursor,.tt-suggestion:hover {
  color: #fff !important;
  background-color: #0097cf !important;

}

.dropdown-menu {
    width: 100% !important;
}

.tt-suggestion p {
  margin: 0 !important;
}
```
