### ISSUE TITLE
Highlight not working

### ISSUE THREAD

**Issue by Malavos** [bassjobsen/Bootstrap-3-Typeahead#164]
Hey there,

I have this CSS Style:

``` CSS

.tt-query {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075) !important;
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075) !important;
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075) !important;
}

.tt-hint {
    color: #999 !important;
}

.tt-menu {    /* used to be tt-dropdown-menu in older versions */
  width: 422px !important;
  margin-top: 4px !important;
  padding: 4px 0 !important;
  background-color: #fff !important;
  border: 1px solid #ccc !important;
  border: 1px solid rgba(0, 0, 0, 0.2) !important;
  -webkit-border-radius: 4px !important;
     -moz-border-radius: 4px !important;
          border-radius: 4px !important;
  -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2) !important;
     -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2) !important;
          box-shadow: 0 5px 10px rgba(0,0,0,.2) !important;
}

.tt-suggestion {
  padding: 3px 20px !important;
  line-height: 24px !important;
}

.tt-suggestion.tt-cursor,.tt-suggestion:hover {
  color: #fff !important;
  background-color: #0097cf !important;

}

.dropdown-menu {
    width: 100% !important;
}

.tt-suggestion p {
  margin: 0 !important;
}
```

Even with that style, the Highlight for the typeahead is not working, and it is enabled on my element:

``` JavaScript

$("#autoCompleteTypeAhead").typeahead({
                    hint: true,
                    highlight: true,
                    minLength: 1,
                    source: arrJson,
                    updater: function (item) {
                        $("#inputHiddenID").val(mappingJson[item]);
                        $("#inputHiddenID").text(mappingJson[item]);
                        $("#inputHiddenID").innertText = mappingJson[item];
                        return item;
                    }
                });

```

This is the result, as you can see, no highlight on the element:

![typeahead](https://cloud.githubusercontent.com/assets/5607619/11099636/3f2d92ce-888b-11e5-8b3d-8952cb238251.png)

How can I enable it to work?
